name: iOS CI

# PR 作成/更新/リオープンなどのタイミングで実行する
on:
  pull_request:
    branches: [ "main" ]
  # 以下によって Actions タブから手動で実行できるようになる
  workflow_dispatch:

# ワークフローに含まれるジョブを定義
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v4
      # Xcode のバージョンを指定
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"
      # iOS 18.2 のシミュレータをインストール
      # 2025/02/26 時点では GitHub Actions で Xcode 16.2 を選択してビルド実行すると以下のエラーが発生するため暫定対処
      # { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device, error:iOS 18.2 is not installed. To use with Xcode, first download and install the platform }
      - name: Install iOS platform
        run: |
          xcodebuild -downloadPlatform iOS -buildVersion 18.2
      # テスト前のビルド
      - name: Build
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild build-for-testing -workspace "AbstinenceSupport.xcworkspace" -scheme "AbstinenceSupport" -configuration Debug -destination "platform=iOS Simulator,name=$device,OS=18.2"
      # テスト実行
      - name: Test
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild test-without-building -workspace "AbstinenceSupport.xcworkspace" -scheme "AbstinenceSupport" -configuration Debug -destination "platform=iOS Simulator,name=$device,OS=18.2"
