name: iOS CI

# PR 作成/更新/リオープンなどのタイミングで実行する
on:
  pull_request:
    branches: [ "main" ]
  # 以下によって Actions タブから手動で実行できるようになる
  workflow_dispatch:

# ワークフローに含まれるジョブを定義
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v4
      # 機密情報をシークレットからコピーして SecureInfo.swift に出力
      - name: Generate Secureinfo file
        env:
          SECURE_INFO: ${{ secrets.ABSTINENCE_SUPPORT_SECURE_INFO }}
        run: |
          echo $SECURE_INFO
          echo $SECURE_INFO > AbstinenceSupportPackage/Sources/AbstinenceSupportCore/SecureInfo.swift
          exit 1
      # Xcode のバージョンを指定
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.1"
      # テスト前のビルド
      - name: Build
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild build-for-testing -workspace "AbstinenceSupport.xcworkspace" -scheme "AbstinenceSupport" -configuration Debug -destination "platform=iOS Simulator,name=$device"
      # テスト実行
      - name: Test
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild build-for-testing -workspace "AbstinenceSupport.xcworkspace" -scheme "AbstinenceSupport" -configuration Debug -destination "platform=iOS Simulator,name=$device"
