name: iOS CI

# PR 作成/更新/リオープンなどのタイミングで実行する
on:
  pull_request:
    branches: [ "main" ]
  # 以下によって Actions タブから手動で実行できるようになる
  workflow_dispatch:

# ワークフローに含まれるジョブを定義
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v4
      # Xcode のバージョンを指定
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          # Xcode 16.2 だと以下のエラーが発生するため、暫定対応として 16.1 にする
          # { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device, error:iOS 18.2 is not installed. To use with Xcode, first download and install the platform }
          # 参考：https://stackoverflow.com/questions/79390065/github-actions-unable-to-find-a-destination-matching-the-provided-destination
          xcode-version: "16.1"
      # テスト前のビルド
      - name: Build
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild build-for-testing -workspace "AbstinenceSupport.xcworkspace" -scheme "AbstinenceSupport" -configuration Debug -destination "platform=iOS Simulator,name=$device"
      # テスト実行
      - name: Test
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild test-without-building -workspace "AbstinenceSupport.xcworkspace" -scheme "AbstinenceSupport" -configuration Debug -destination "platform=iOS Simulator,name=$device"
